const DEMO_PROJECTS = [
  {
    id: 1,
    name: 'DevTrack Dashboard',
    description: 'Full-stack developer productivity dashboard with GitHub, LeetCode, and HackerRank integrations. Real-time analytics, job match scoring, and achievement tracking.',
    image: null,
    status: 'completed',
    techStack: ['React', 'Vite', 'Tailwind CSS', 'Express', 'SQLite', 'Recharts'],
    startDate: '2025-11-15',
    updatedAt: '2026-07-20',
    completion: 95,
    githubUrl: 'https://github.com/Naveen-hub-design/Dev-Tracker',
    liveUrl: null,
    features: ['Authentication', 'Dashboard Analytics', 'Multi-platform Integration', 'Job Match Scoring'],
    challenges: ['HackerRank API blocks server-side requests', 'CORS configuration for multiple origins'],
    futureImprovements: ['Real-time WebSocket updates', 'Mobile app version', 'Team collaboration features'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2025-11-15', label: 'Project Started' },
      { date: '2025-12-01', label: 'Auth System Complete' },
      { date: '2026-01-10', label: 'GitHub Integration' },
      { date: '2026-03-15', label: 'LeetCode + HackerRank' },
      { date: '2026-06-01', label: 'Premium Dashboard Redesign' },
      { date: '2026-07-20', label: 'Deployed to Production' },
    ],
  },
  {
    id: 2,
    name: 'E-Commerce Platform',
    description: 'Full-featured e-commerce platform with product catalog, cart management, secure checkout, and admin dashboard for inventory management.',
    image: null,
    status: 'in_progress',
    techStack: ['React', 'Node.js', 'MongoDB', 'Stripe', 'Redux'],
    startDate: '2026-03-01',
    updatedAt: '2026-07-18',
    completion: 72,
    githubUrl: 'https://github.com/Naveen-hub-design/ecommerce-app',
    liveUrl: null,
    features: ['Product Catalog', 'Shopping Cart', 'Payment Processing', 'Admin Panel'],
    challenges: ['Payment integration complexity', 'Inventory synchronization'],
    futureImprovements: ['Recommendation engine', 'Multi-vendor support', 'Progressive Web App'],
    contributors: ['Naveen', 'Priya'],
    milestones: [
      { date: '2026-03-01', label: 'Project Started' },
      { date: '2026-04-10', label: 'Product Catalog Complete' },
      { date: '2026-05-20', label: 'Cart & Checkout' },
      { date: '2026-07-18', label: 'Admin Dashboard' },
    ],
  },
  {
    id: 3,
    name: 'DSA Solutions Repository',
    description: 'Comprehensive collection of Data Structures and Algorithms solutions with complexity analysis, visual explanations, and test cases.',
    image: null,
    status: 'in_progress',
    techStack: ['Python', 'JavaScript', 'C++'],
    startDate: '2025-08-10',
    updatedAt: '2026-07-22',
    completion: 65,
    githubUrl: 'https://github.com/Naveen-hub-design/dsa-solutions',
    liveUrl: null,
    features: ['200+ Solutions', 'Complexity Analysis', 'Visual Explanations', 'Test Cases'],
    challenges: ['Maintaining consistency across languages', 'Creating clear explanations'],
    futureImprovements: ['Interactive visualizations', 'Difficulty-based progression', 'Mock interview mode'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2025-08-10', label: 'Repository Created' },
      { date: '2025-12-01', label: '100 Solutions Milestone' },
      { date: '2026-06-15', label: 'Language Expansion' },
    ],
  },
  {
    id: 4,
    name: 'Portfolio Website',
    description: 'Personal portfolio showcasing projects, skills, and blog posts with modern design, dark mode, and responsive layout.',
    image: null,
    status: 'completed',
    techStack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    startDate: '2025-06-01',
    updatedAt: '2026-04-10',
    completion: 100,
    githubUrl: 'https://github.com/Naveen-hub-design/portfolio-site',
    liveUrl: 'https://naveen-dev.com',
    features: ['Responsive Design', 'Dark Mode', 'Blog System', 'Contact Form'],
    challenges: ['Cross-browser compatibility', 'Performance optimization'],
    futureImprovements: ['MDX blog support', 'RSS feed', 'Analytics integration'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2025-06-01', label: 'Project Started' },
      { date: '2025-07-15', label: 'Design Complete' },
      { date: '2025-08-01', label: 'Deployed' },
    ],
  },
  {
    id: 5,
    name: 'Node.js API Boilerplate',
    description: 'Production-ready Node.js REST API boilerplate with authentication, rate limiting, logging, Docker support, and CI/CD pipeline.',
    image: null,
    status: 'completed',
    techStack: ['Node.js', 'Express', 'Docker', 'PostgreSQL', 'Redis'],
    startDate: '2025-09-20',
    updatedAt: '2026-02-15',
    completion: 100,
    githubUrl: 'https://github.com/Naveen-hub-design/node-api-boilerplate',
    liveUrl: null,
    features: ['JWT Auth', 'Rate Limiting', 'Docker Setup', 'CI/CD Pipeline'],
    challenges: ['Docker multi-stage build optimization', 'Testing environment parity'],
    futureImprovements: ['GraphQL support', 'Microservice templates', 'OpenAPI documentation'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2025-09-20', label: 'Project Started' },
      { date: '2025-10-15', label: 'Core Features' },
      { date: '2025-12-01', label: 'Docker + CI/CD' },
    ],
  },
  {
    id: 6,
    name: 'Task Management App',
    description: 'Kanban-style task management application with drag-and-drop, team collaboration, labels, and real-time updates.',
    image: null,
    status: 'planned',
    techStack: ['React', 'TypeScript', 'Supabase', 'DnD Kit'],
    startDate: '2026-08-01',
    updatedAt: '2026-07-10',
    completion: 15,
    githubUrl: null,
    liveUrl: null,
    features: ['Kanban Board', 'Drag & Drop', 'Team Workspaces', 'Real-time Sync'],
    challenges: ['Real-time conflict resolution', 'Offline support'],
    futureImprovements: ['AI task prioritization', 'Calendar integration', 'Mobile app'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2026-07-10', label: 'Planning Complete' },
      { date: '2026-08-01', label: 'Development Start' },
    ],
  },
  {
    id: 7,
    name: 'AI Chat Interface',
    description: 'Chat interface for interacting with language models with streaming responses, conversation history, and markdown rendering.',
    image: null,
    status: 'archived',
    techStack: ['React', 'OpenAI API', 'WebSocket', 'Tailwind CSS'],
    startDate: '2025-10-05',
    updatedAt: '2026-01-20',
    completion: 80,
    githubUrl: null,
    liveUrl: null,
    features: ['Streaming Responses', 'Conversation History', 'Markdown Rendering', 'Code Highlighting'],
    challenges: ['WebSocket reconnection handling', 'Token management'],
    futureImprovements: ['Multi-model support', 'File upload', 'Voice input'],
    contributors: ['Naveen'],
    milestones: [
      { date: '2025-10-05', label: 'Project Started' },
      { date: '2025-11-20', label: 'Core Chat Working' },
      { date: '2026-01-20', label: 'Archived' },
    ],
  },
];

export async function fetchProjects() {
  await new Promise((r) => setTimeout(r, 300));
  return DEMO_PROJECTS;
}

export async function fetchProjectById(id) {
  await new Promise((r) => setTimeout(r, 200));
  return DEMO_PROJECTS.find((p) => p.id === id) || null;
}
